[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wordllama"
version = "0.1.0"
description = "WordLlama Embedding and Training"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.6"
authors = [{ name = "Lee Miller", email = "dleemiller@gmail.com" }]
dependencies = [
  "numpy",
  "safetensors",
  "tokenizers",
  "toml",
  "pydantic>=2"
]

[project.optional-dependencies]
train = [
    "accelerate",
    "torch>=2",
    "transformers>=4",
    "sentence-transformers",
    "datasets",
]

[project.urls]
Homepage = ""
Repository = "https://github.com/dleemiller/WordLlama"

[project.scripts]
wordllama = "wordllama.wordllama:main"

[tool.setuptools.package-data]
wordllama = ["**/*.toml"]

