[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wordllama"
version = "0.1.0"
description = "WordLlama Embedding and Training"
authors = ["Lee Miller <dleemiller@gmail.com>"]
license = "MIT"
readme = "README.md"
requires-python = ">=3.6"

[project.urls]
"Homepage" = ""
"Repository" = "https://github.com/dleemiller/WordLlama"

[project.dependencies]
numpy = "*"
safetensors = "*"
tokenizers = "*"
toml = "*"

[project.optional-dependencies]
train = [
    "torch",
    "transformers",
    "sentence-transformers",
    "datasets"
]

[tool.setuptools.package-data]
"wordllama" = ["**/*.toml"]

[tool.setuptools.entry-points.console_scripts]
wordllama = "wordllama.wordllama:main"

