name: Upload Python Package

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel twine cibuildwheel delocate

    - name: Ensure Docker service is running
      if: runner.os == 'Linux'
      run: |
        sudo service docker start

    - name: Build package
      env:
        CIBW_ARCHS_MACOS: "x86_64 arm64"
        CIBW_ARCHS_LINUX: "x86_64 i686"
        CIBW_ARCHS_WINDOWS: "x86_64"
      run: |
        cibuildwheel --platform auto --output-dir wheelhouse

    - name: List wheelhouse contents
      run: ls -l wheelhouse

    - name: List wheel dependencies
      if: matrix.os == 'macos-latest'
      run: |
        delocate-listdeps wheelhouse/*.whl

    - name: Repair wheel
      if: matrix.os == 'macos-latest'
      run: |
        delocate-wheel --require-archs x86_64 -w repaired_wheel wheelhouse/*.whl

    - name: Publish package
      if: github.event_name == 'push'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload wheelhouse/*

